Fix broken Netlify build
I have no idea why but Netlify chokes on the first opening brace and
reports an error on a different line in this file. I had to guess which
part of the content was triggering the error because the location
information in the error message was bogus.

$ npx vitepress build .

  vitepress v1.3.1

x Build failed in 427ms
✖ building client + server bundles...
build error:
[vite:vue] [plugin vite:vue] api/clients/typescript.md (32:85): Error
parsing JavaScript expression: Unexpected token, expected "," (1:4)
file:
/home/alco/code/electric-sql/next/docs/api/clients/typescript.md:32:85
[vite:vue] [plugin vite:vue] api/clients/typescript.md (32:85): Error
parsing JavaScript expression: Unexpected token, expected "," (1:4)
file:
/home/alco/code/electric-sql/next/docs/api/clients/typescript.md:32:85
SyntaxError: Error parsing JavaScript expression: Unexpected token,
expected "," (1:4)